"""Add indexes to Score table for performance optimization

Revision ID: 2ff2059bfbb1
Revises: 202511110400
Create Date: 2025-11-11 19:37:57.503441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ff2059bfbb1'
down_revision = '202511110400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.create_index('idx_quiz_name', ['quiz_name'], unique=False)
        batch_op.create_index('idx_quiz_score', ['quiz_name', 'score'], unique=False)
        batch_op.create_index('idx_user_date', ['user_id', 'date_taken'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_index('idx_user_date')
        batch_op.drop_index('idx_quiz_score')
        batch_op.drop_index('idx_quiz_name')

    # ### end Alembic commands ###
