"""Add streak fields to User model

Revision ID: c0979da4221d
Revises: 2ff2059bfbb1
Create Date: 2025-11-15 13:23:03.190816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0979da4221d'
down_revision = '2ff2059bfbb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_streak', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('longest_streak', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('last_quiz_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_quiz_date')
        batch_op.drop_column('longest_streak')
        batch_op.drop_column('current_streak')

    # ### end Alembic commands ###
